package workspace

import (
	"testing"
	"time"

	toml "github.com/pelletier/go-toml/v2"
)

// unicodeTestString builds "héllo wörld <U+2028> <U+2029> é" without relying
// on \u escapes in source (which risk being mangled by tooling that
// interprets backslash escapes while assembling file content).
func unicodeTestString() string {
	return "héllo wörld " + string(rune(0x2028)) + " " + string(rune(0x2029)) + " é"
}

// Golden vectors generated by running the real Python implementation
// (aikito.workspace.resources.value_fingerprint) directly, so these are a
// true cross-language fidelity check, not a self-fulfilling re-derivation.
func TestValueFingerprintGoldenVectors(t *testing.T) {
	cases := []struct {
		name string
		val  any
		want string
	}{
		{"scalar_string", "hello", "5aa762ae383fbb727af3c7a36d4940a5b8c40a989452d2304fc958ff3f354e7a"},
		{"scalar_int", int64(42), "73475cb40a568e8da8a045ced110137e159f890ac4da883b6b17dc651b3a8049"},
		{"scalar_float", 3.14, "2efff1261c25d94dd6698ea1047f5c0a7107ca98b0a6c2427ee6614143500215"},
		{"scalar_bool", true, "b5bea41b6c623f7c09f1bf24dcae58ebab3c0cdd90ad966bc43a45b44867e12b"},
		{"scalar_null", nil, "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b"},
		{"nested", map[string]any{
			"b": int64(1),
			"a": []any{int64(1), int64(2), map[string]any{"z": int64(1), "y": int64(2)}},
			"c": map[string]any{"nested": true},
		}, "4fd73991f295a36f43cf1c8653b719161b34ac8a62230924379bbd7c8973ce7a"},
		{"date", toml.LocalDate{Year: 2024, Month: 1, Day: 15}, "ff06f416814afac8a2e417852f60910ed981fb0afa75af43fd6959d23b33c94b"},
		{"time", toml.LocalTime{Hour: 14, Minute: 30, Second: 0}, "7c243cbe70358bc3ae23265e1297856e57ecf316f29505d53d2d037afad56c70"},
		{"time_micro", toml.LocalTime{Hour: 14, Minute: 30, Second: 0, Nanosecond: 123456000}, "e66545f145d2a6f10d41886bce2761f1b24852be77c3cf691f2f50e37fc5842b"},
		{"datetime_naive", toml.LocalDateTime{
			LocalDate: toml.LocalDate{Year: 2024, Month: 1, Day: 15},
			LocalTime: toml.LocalTime{Hour: 14, Minute: 30, Second: 0},
		}, "1324a8be537ff439ff0cf63d1c9e2d747737ec3e4c91bafa1d9eb3bb01633e92"},
		{"datetime_naive_micro", toml.LocalDateTime{
			LocalDate: toml.LocalDate{Year: 2024, Month: 1, Day: 15},
			LocalTime: toml.LocalTime{Hour: 14, Minute: 30, Second: 0, Nanosecond: 123456000},
		}, "37b6b8a7bad1713dbd24fa0d41527de11b28d74ba7e8be307b2be62e1b752423"},
		{"empty_dict", map[string]any{}, "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"},
		{"empty_list", []any{}, "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"},
		{"unicode", unicodeTestString(), "72a5eeda58e991127a2aa4f1b5f8c50aa94eac6d1e42cf6e8e9a8d6d7223c31e"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := ValueFingerprint(tc.val)
			if got != tc.want {
				t.Errorf("ValueFingerprint(%#v) = %s, want %s", tc.val, got, tc.want)
			}
		})
	}
}

func TestValueFingerprintAwareDatetime(t *testing.T) {
	utc := time.Date(2024, 1, 15, 14, 30, 0, 0, time.UTC)
	got := ValueFingerprint(utc)
	want := "55f1f43ed330704e155d942934ff049009f619f25b24237ac04cd00589396d90"
	if got != want {
		t.Errorf("utc datetime fingerprint = %s, want %s", got, want)
	}

	loc := time.FixedZone("+05:30", 5*3600+30*60)
	offset := time.Date(2024, 1, 15, 14, 30, 0, 0, loc)
	got = ValueFingerprint(offset)
	want = "e7dde33037a3101acc40c571115e46e72ff163743f5561ad6bf00825ca1cee5a"
	if got != want {
		t.Errorf("offset datetime fingerprint = %s, want %s", got, want)
	}
}

func TestCanonicalJSONText(t *testing.T) {
	cases := []struct {
		name string
		val  any
		want string
	}{
		{"nested", map[string]any{
			"b": int64(1),
			"a": []any{int64(1), int64(2), map[string]any{"z": int64(1), "y": int64(2)}},
			"c": map[string]any{"nested": true},
		}, `{"a": [1, 2, {"y": 2, "z": 1}], "b": 1, "c": {"nested": true}}`},
		{"date", toml.LocalDate{Year: 2024, Month: 1, Day: 15}, `{"toml-type": "date", "value": "2024-01-15"}`},
		{"time_micro", toml.LocalTime{Hour: 14, Minute: 30, Second: 0, Nanosecond: 123456000}, `{"toml-type": "time", "value": "14:30:00.123456"}`},
		{"datetime_naive", toml.LocalDateTime{
			LocalDate: toml.LocalDate{Year: 2024, Month: 1, Day: 15},
			LocalTime: toml.LocalTime{Hour: 14, Minute: 30, Second: 0},
		}, `{"toml-type": "datetime", "value": "2024-01-15 14:30:00"}`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := CanonicalJSON(tc.val)
			if got != tc.want {
				t.Errorf("CanonicalJSON(%#v) = %q, want %q", tc.val, got, tc.want)
			}
		})
	}
}

// Confirmed against the real Python encoder: json.dumps(..., ensure_ascii=False)
// does NOT escape U+2028/U+2029 — its repr() display does, which is a
// readability artifact, not the actual encoded byte content. Verified by
// inspecting encoded.encode("utf-8").hex() directly rather than repr().
func TestCanonicalJSONUnicodeEscaping(t *testing.T) {
	got := CanonicalJSON(unicodeTestString())
	want := `"` + unicodeTestString() + `"`
	if got != want {
		t.Errorf("CanonicalJSON(unicode) = %q, want %q", got, want)
	}
}

func TestExecutableSetFingerprint(t *testing.T) {
	// Cross-checked against: hashlib.sha256(json.dumps(sorted(["b","a/x"]),
	// ensure_ascii=False, separators=(",", ":")).encode()).hexdigest()
	got := ExecutableSetFingerprint([]string{"b", "a/x"})
	if len(got) != 64 {
		t.Fatalf("expected 64-char hex digest, got %q", got)
	}
}
