package workspace

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type localResourceCase struct {
	ID          string     `json:"id"`
	OK          bool       `json:"ok"`
	Kind        string     `json:"kind"`
	Name        string     `json:"name"`
	Fingerprint string     `json:"fingerprint"`
	Parts       [][]string `json:"parts"`
	References  []string   `json:"references"`
	Error       string     `json:"error"`
}

// TestLocalResourceForIDAgainstPython cross-validates LocalResourceForID
// against testdata/local_resource_for_id_expected.json, generated by
// running the real Python local_resource_for_id across 22 cases covering
// every kind plus several deliberate error paths (host-local config,
// structural project-field collision, project ID with a slash, an unknown
// kind, a global-instructions name mismatch).
func TestLocalResourceForIDAgainstPython(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "local_resource_for_id_expected.json"))
	if err != nil {
		t.Fatal(err)
	}
	var cases []localResourceCase
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatal(err)
	}

	for _, tc := range cases {
		t.Run(tc.ID, func(t *testing.T) {
			fingerprint := tc.Fingerprint
			got, err := LocalResourceForID(tc.ID, fingerprint)
			if !tc.OK {
				if err == nil {
					t.Fatalf("expected an error, got resource %+v", got)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got.Kind != tc.Kind || got.Name != tc.Name || got.Fingerprint != tc.Fingerprint {
				t.Errorf("got kind=%q name=%q fingerprint=%q, want kind=%q name=%q fingerprint=%q",
					got.Kind, got.Name, got.Fingerprint, tc.Kind, tc.Name, tc.Fingerprint)
			}
			if len(got.Parts) != len(tc.Parts) {
				t.Fatalf("parts = %v, want %v", got.Parts, tc.Parts)
			}
			for i, p := range tc.Parts {
				if got.Parts[i].Path != p[0] || got.Parts[i].Table != p[1] {
					t.Errorf("part[%d] = %+v, want path=%q table=%q", i, got.Parts[i], p[0], p[1])
				}
			}
			gotRefs := got.References
			if gotRefs == nil {
				gotRefs = []string{}
			}
			wantRefs := tc.References
			if wantRefs == nil {
				wantRefs = []string{}
			}
			if !equalStringSlices(gotRefs, wantRefs) {
				t.Errorf("references = %v, want %v", gotRefs, wantRefs)
			}
		})
	}
}
