package workspace

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// buildSnapshotFixture recreates, byte-for-byte, the fixture workspace tree
// used to generate testdata/snapshot_fixture_expected.json by running the
// real Python snapshot_workspace directly (see the session notes: this is
// the same cross-language golden-vector methodology used throughout this
// package's tests). Keep this function and the fixture tree that produced
// the JSON in sync if either changes.
func buildSnapshotFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	write := func(rel, content string) {
		path := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	if err := os.MkdirAll(filepath.Join(root, "agents"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "subagents"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "mcps"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "skills", "empty-skill"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "skills", "empty-dir-skill", "empty", "nested"), 0o755); err != nil {
		t.Fatal(err)
	}

	write("layout.toml", "version = 2\n")
	write("skills.toml", "skills = [\"my-skill\", \"aikito\"]\n")
	write("config.toml", "[memory]\nstale_days = 45\n\n[inbox]\npath = \"inbox\"\n")
	write("global/AGENTS.md", "# Global instructions\nBe helpful.\n")
	write("memory/general.md", "# General memory\n")
	write("memory/notes/decision-1.md", "# Decision 1\n")
	write("skills/my-skill/SKILL.md", "---\nname: my-skill\n---\nDo stuff.\n")
	write("skills/my-skill/bin/run.sh", "#!/bin/sh\necho hi\n")
	if err := os.Chmod(filepath.Join(root, "skills/my-skill/bin/run.sh"), 0o755); err != nil {
		t.Fatal(err)
	}
	write("skills/empty-dir-skill/SKILL.md", "---\nname: empty-dir-skill\n---\nHas an empty nested dir.\n")
	write("agents/codex.toml", "[agents.codex]\ndisplay_name = \"Codex\"\ninstruction_path = \".codex/AGENTS.md\"\n")
	write("subagents/reviewer.md", "---\ndescription: \"Reviews code\"\nagents: [\"codex\"]\n---\nReview the code carefully.\n")
	write("mcps/filesystem.toml", "agents = [\"codex\"]\nurl = \"http://localhost:1234\"\n")
	write("projects/proj1/agent.toml", "skills = [\"my-skill\"]\nsync_mode = \"link\"\n\n[paths]\nwork = \"/tmp/proj1\"\n")
	write("projects/proj1/AGENTS.md", "# Project instructions\n")
	write("projects/proj1/memory/notes/arch.md", "# Architecture\n")
	write("inbox/idea.md", "# An idea\n")

	return root
}

type expectedResource struct {
	Fingerprint     string     `json:"fingerprint"`
	Parts           [][]string `json:"parts"`
	References      []string   `json:"references"`
	ModeFingerprint *string    `json:"mode_fingerprint"`
}

type expectedFinding struct {
	Status   string `json:"status"`
	Code     string `json:"code"`
	Resource string `json:"resource"`
	Message  string `json:"message"`
}

type expectedSnapshot struct {
	Resources map[string]expectedResource `json:"resources"`
	Findings  []expectedFinding           `json:"findings"`
	Skipped   []string                    `json:"skipped"`
}

// TestSnapshotWorkspaceAgainstPython cross-validates SnapshotWorkspace
// against testdata/snapshot_fixture_expected.json, which was generated by
// running the real Python snapshot_workspace on the identical fixture tree
// (see buildSnapshotFixture's doc comment).
func TestSnapshotWorkspaceAgainstPython(t *testing.T) {
	root := buildSnapshotFixture(t)

	data, err := os.ReadFile(filepath.Join("testdata", "snapshot_fixture_expected.json"))
	if err != nil {
		t.Fatal(err)
	}
	var want expectedSnapshot
	if err := json.Unmarshal(data, &want); err != nil {
		t.Fatal(err)
	}

	snap, err := SnapshotWorkspace(root, root)
	if err != nil {
		t.Fatalf("SnapshotWorkspace error: %v", err)
	}

	if len(snap.Resources) != len(want.Resources) {
		gotIDs := make([]string, 0, len(snap.Resources))
		for id := range snap.Resources {
			gotIDs = append(gotIDs, id)
		}
		t.Fatalf("resource count = %d, want %d\ngot ids: %v", len(snap.Resources), len(want.Resources), gotIDs)
	}
	for id, wantRes := range want.Resources {
		gotRes, ok := snap.Resources[id]
		if !ok {
			t.Errorf("missing resource %q", id)
			continue
		}
		if gotRes.Fingerprint != wantRes.Fingerprint {
			t.Errorf("%s: fingerprint = %q, want %q", id, gotRes.Fingerprint, wantRes.Fingerprint)
		}
		if len(gotRes.Parts) != len(wantRes.Parts) {
			t.Errorf("%s: parts = %v, want %v", id, gotRes.Parts, wantRes.Parts)
		} else {
			for i, p := range wantRes.Parts {
				if gotRes.Parts[i].Path != p[0] || gotRes.Parts[i].Table != p[1] {
					t.Errorf("%s: part[%d] = %+v, want path=%q table=%q", id, i, gotRes.Parts[i], p[0], p[1])
				}
			}
		}
		gotRefs := gotRes.References
		if gotRefs == nil {
			gotRefs = []string{}
		}
		wantRefs := wantRes.References
		if wantRefs == nil {
			wantRefs = []string{}
		}
		if !equalStringSlices(gotRefs, wantRefs) {
			t.Errorf("%s: references = %v, want %v", id, gotRefs, wantRefs)
		}
		if (gotRes.ModeFingerprint == nil) != (wantRes.ModeFingerprint == nil) {
			t.Errorf("%s: mode_fingerprint presence mismatch: got %v want %v", id, gotRes.ModeFingerprint, wantRes.ModeFingerprint)
		} else if gotRes.ModeFingerprint != nil && *gotRes.ModeFingerprint != *wantRes.ModeFingerprint {
			t.Errorf("%s: mode_fingerprint = %q, want %q", id, *gotRes.ModeFingerprint, *wantRes.ModeFingerprint)
		}
	}

	if len(snap.Findings) != len(want.Findings) {
		t.Fatalf("findings = %+v, want %+v", snap.Findings, want.Findings)
	}
	for i, wf := range want.Findings {
		gf := snap.Findings[i]
		if gf.Status != wf.Status || gf.Code != wf.Code || gf.Resource != wf.Resource {
			t.Errorf("finding[%d] = %+v, want %+v", i, gf, wf)
		}
	}

	gotSkipped := snap.Skipped
	if gotSkipped == nil {
		gotSkipped = []string{}
	}
	wantSkipped := want.Skipped
	if wantSkipped == nil {
		wantSkipped = []string{}
	}
	if !equalStringSlices(gotSkipped, wantSkipped) {
		t.Errorf("skipped = %v, want %v", gotSkipped, wantSkipped)
	}
}
