package mcp

import (
	"encoding/json"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"
	"unicode"
)

// redactVectors is generated by running the real Python implementation
// (aikito/mcp/redact.py) — see testdata/redact_vectors.json. Every expected
// value below comes from live Python output, not hand-derived expectations.
// Regenerate with testdata/gen_redact_vectors.py (see redactVectorsSource).
type redactVectors struct {
	SensitiveParam     [][2]any `json:"sensitive_param"`
	CredentialHeader   [][2]any `json:"credential_header"`
	Loopback           [][2]any `json:"loopback"`
	HasSensitiveParams [][2]any `json:"has_sensitive_params"`
	ProbeError         []struct {
		Text    string            `json:"text"`
		Headers map[string]string `json:"headers"`
		Want    string            `json:"want"`
	} `json:"probe_error"`
	Partition           [][5]string `json:"partition"`
	URLsInText          [][2]any    `json:"urls_in_text"`
	IsAuthorizationURL  [][2]any    `json:"is_authorization_url"`
	RedactSensitiveURLs [][2]string `json:"redact_sensitive_urls"`
	PrintableRanges     [][2]int    `json:"printable_ranges"`
	PythonUnicode       string      `json:"python_unicode_version"`
}

// redactVectorsSource is produced by testdata/gen_redact_vectors.py, which
// imports aikito.mcp.redact from the reference checkout (AIKITO_PYTHON_SRC,
// else a sibling ../aikito/src) and records each function's actual return
// value for a fixed set of inputs, plus run-length ranges of every code
// point for which str.isprintable() is True. Regenerate with:
//
//	python3 internal/mcp/testdata/gen_redact_vectors.py
const redactVectorsSource = "testdata/redact_vectors.json"

func loadRedactVectors(t *testing.T) redactVectors {
	t.Helper()
	data, err := os.ReadFile(redactVectorsSource)
	if err != nil {
		t.Fatal(err)
	}
	var v redactVectors
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatal(err)
	}
	return v
}

func boolCases(t *testing.T, name string, cases [][2]any, fn func(string) bool) {
	t.Helper()
	if len(cases) == 0 {
		t.Fatalf("%s: no vectors loaded", name)
	}
	for _, c := range cases {
		in, want := c[0].(string), c[1].(bool)
		if got := fn(in); got != want {
			t.Errorf("%s(%q) = %v, Python says %v", name, in, got, want)
		}
	}
}

func TestIsSensitiveURLParameterMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	boolCases(t, "IsSensitiveURLParameter", v.SensitiveParam, IsSensitiveURLParameter)

	// Guard against the vector set silently losing its negative cases:
	// over-redaction breaks legitimate output just as surely as
	// under-redaction leaks secrets.
	negatives := 0
	for _, c := range v.SensitiveParam {
		if !c[1].(bool) {
			negatives++
		}
	}
	if negatives < 20 {
		t.Errorf("expected at least 20 non-sensitive parameter vectors, got %d", negatives)
	}
}

func TestIsCredentialHeaderMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	boolCases(t, "IsCredentialHeader", v.CredentialHeader, IsCredentialHeader)
}

func TestIsLoopbackURLMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	boolCases(t, "IsLoopbackURL", v.Loopback, IsLoopbackURL)
}

func TestHasSensitiveParametersMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	boolCases(t, "hasSensitiveParameters", v.HasSensitiveParams, hasSensitiveParameters)
}

func TestIsAuthorizationURLMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	boolCases(t, "IsAuthorizationURL", v.IsAuthorizationURL, IsAuthorizationURL)
}

func TestRedactProbeErrorMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	if len(v.ProbeError) == 0 {
		t.Fatal("no probe_error vectors loaded")
	}
	for _, c := range v.ProbeError {
		got := RedactProbeError(c.Text, c.Headers)
		if got != c.Want {
			t.Errorf("RedactProbeError(%q, %v)\n got: %q\nwant: %q", c.Text, c.Headers, got, c.Want)
		}
		// Independent of Python parity: no credential header value may
		// ever survive into the output.
		for name, value := range c.Headers {
			if value != "" && IsCredentialHeader(name) && strings.Contains(got, value) {
				t.Errorf("RedactProbeError leaked %s value %q in %q", name, value, got)
			}
		}
		if n := len([]rune(got)); n > 300 {
			t.Errorf("RedactProbeError output is %d runes, want <= 300", n)
		}
	}
}

func TestPartitionMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	for _, c := range v.Partition {
		before, sep, after := partition(c[0], c[1])
		if got := [3]string{before, sep, after}; got != [3]string{c[2], c[3], c[4]} {
			t.Errorf("partition(%q, %q) = %q, Python says %q", c[0], c[1], got, c[2:])
		}
	}
}

func TestURLsInTextMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	for _, c := range v.URLsInText {
		in := c[0].(string)
		var want []string
		for _, u := range c[1].([]any) {
			want = append(want, u.(string))
		}
		got := URLsInText(in)
		if len(got) == 0 && len(want) == 0 {
			continue
		}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("URLsInText(%q) = %q, Python says %q", in, got, want)
		}
	}
}

func TestRedactSensitiveURLsMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	for _, c := range v.RedactSensitiveURLs {
		if got := RedactSensitiveURLs(c[0]); got != c[1] {
			t.Errorf("RedactSensitiveURLs(%q)\n got: %q\nwant: %q", c[0], got, c[1])
		}
	}
}

// TestIsPrintableMatchesPython checks isPrintable against Python's
// str.isprintable() exhaustively over every Unicode code point.
//
// Strict in the direction that matters: no character may be printable in
// Go but not in Python (that would let a control/format character through
// into user-visible probe error text). The reverse direction is tolerated
// only for Unicode-version lag — characters assigned in Python's newer
// Unicode tables that Go's tables don't know yet, which Go conservatively
// replaces with a space. Those must all be letters/marks/symbols etc. that
// Go considers unassigned, never something Go knows to be a control or
// separator.
func TestIsPrintableMatchesPython(t *testing.T) {
	v := loadRedactVectors(t)
	if len(v.PrintableRanges) == 0 {
		t.Fatal("no printable_ranges vectors loaded")
	}
	pyPrintable := func(r rune) bool {
		i := sort.Search(len(v.PrintableRanges), func(i int) bool { return v.PrintableRanges[i][1] >= int(r) })
		return i < len(v.PrintableRanges) && v.PrintableRanges[i][0] <= int(r)
	}
	lag := 0
	for c := rune(0); c <= unicode.MaxRune; c++ {
		if c >= 0xD800 && c <= 0xDFFF {
			continue // surrogates are not valid runes in Go strings
		}
		py, got := pyPrintable(c), isPrintable(c)
		switch {
		case got && !py:
			t.Errorf("isPrintable(U+%04X) = true, Python says false", c)
		case !got && py:
			// Must be a code point Go's tables don't assign at all.
			if unicode.In(c, unicode.Cc, unicode.Cf, unicode.Co, unicode.Zs, unicode.Zl, unicode.Zp) {
				t.Errorf("isPrintable(U+%04X) = false for a character Go categorises as control/format/separator, but Python says printable", c)
			}
			lag++
		}
	}
	t.Logf("Python Unicode %s vs Go Unicode %s: %d code points printable only in Python (version lag)", v.PythonUnicode, unicode.Version, lag)
}

// Security-relevant characters asserted explicitly (in addition to the
// exhaustive check above), so a regression shows up by name.
func TestIsPrintableRejectsDangerousCharacters(t *testing.T) {
	nonPrintable := map[rune]string{
		0x00: "NUL", 0x07: "BEL", 0x08: "BS", 0x09: "TAB", 0x0A: "LF", 0x0D: "CR", 0x1B: "ESC",
		0x7F: "DEL", 0x85: "NEL", 0x9B: "CSI", 0xA0: "NBSP", 0xAD: "SOFT HYPHEN",
		0x200B: "ZERO WIDTH SPACE", 0x200D: "ZERO WIDTH JOINER", 0x2003: "EM SPACE", 0x3000: "IDEOGRAPHIC SPACE",
		0x2028: "LINE SEPARATOR", 0x2029: "PARAGRAPH SEPARATOR",
		0x202E: "RIGHT-TO-LEFT OVERRIDE", 0x2066: "LEFT-TO-RIGHT ISOLATE", 0xFEFF: "BOM",
		0xE000: "PRIVATE USE", 0x10FFFF: "NONCHARACTER",
	}
	for r, name := range nonPrintable {
		if isPrintable(r) {
			t.Errorf("isPrintable(U+%04X %s) = true, want false", r, name)
		}
	}
	for _, r := range []rune{' ', 'a', '~', 0xE9, 0x4E2D, 0x1F600, 0x0301} {
		if !isPrintable(r) {
			t.Errorf("isPrintable(U+%04X) = false, want true", r)
		}
	}
}
