package cli

import (
	"bytes"
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// adopt_vectors.json is the reference CLI's behaviour for each scenario,
// generated by testdata/adopt/gen_adopt_vectors.py (which also documents
// the format). Every step's stdout, stderr and exit code and the final HOME
// tree must match.
type adoptVectorStep struct {
	Args   []string `json:"args"`
	Stdout *string  `json:"stdout"`
	Stderr *string  `json:"stderr"`
	Exit   int      `json:"exit"`
}

type adoptVector struct {
	Files map[string]*string `json:"files"`
	Steps []adoptVectorStep  `json:"steps"`
	Tree  map[string]string  `json:"tree"`
}

var adoptTimestamp = regexp.MustCompile(`adopt_\d{8}_\d{6}`)

func adoptNormalise(s, home string) string {
	return adoptTimestamp.ReplaceAllString(strings.ReplaceAll(s, home, "H"), "adopt_TS")
}

// adoptSnapshot mirrors the generator's snapshot(): HOME without the
// workspace's .git and bundled skills; symlinks as "-> target", empty
// directories as "<dir>", files by content.
func adoptSnapshot(t *testing.T, home string) map[string]string {
	t.Helper()
	tree := map[string]string{}
	err := filepath.WalkDir(home, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if path == home {
			return nil
		}
		rel := filepath.ToSlash(strings.TrimPrefix(path, home+string(filepath.Separator)))
		key := adoptNormalise(rel, home)
		if d.Type()&fs.ModeSymlink != 0 {
			target, _ := os.Readlink(path)
			tree[key] = "-> " + adoptNormalise(target, home)
			return nil
		}
		if d.IsDir() {
			if rel == "aikito/.git" || rel == "aikito/skills" {
				return filepath.SkipDir
			}
			entries, _ := os.ReadDir(path)
			if len(entries) == 0 {
				tree[key] = "<dir>"
			}
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		tree[key] = adoptNormalise(strings.ToValidUTF8(string(data), "\uFFFD"), home)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return tree
}

func TestAdoptMatchesPythonScenarios(t *testing.T) {
	data, err := os.ReadFile("testdata/adopt/adopt_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var vectors map[string]adoptVector
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatal(err)
	}
	names := make([]string, 0, len(vectors))
	for n := range vectors {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, name := range names {
		v := vectors[name]
		t.Run(name, func(t *testing.T) {
			env := testEnv(t)
			env.Cwd = env.Home
			t.Chdir(env.Home) // a relative adopt target resolves against the process cwd
			for rel, content := range v.Files {
				p := filepath.Join(env.Home, filepath.FromSlash(rel))
				if content == nil {
					mustMkdirAll(t, p)
				} else {
					mustMkdirAll(t, filepath.Dir(p))
					writeFile(t, p, *content)
				}
			}
			for _, want := range v.Steps {
				if op := want.Args[0]; op == "__write__" || op == "__append__" {
					p := filepath.Join(env.Home, filepath.FromSlash(want.Args[1]))
					mustMkdirAll(t, filepath.Dir(p))
					flag := os.O_CREATE | os.O_WRONLY | os.O_TRUNC
					if op == "__append__" {
						flag = os.O_CREATE | os.O_WRONLY | os.O_APPEND
					}
					f, err := os.OpenFile(p, flag, 0o644)
					if err != nil {
						t.Fatal(err)
					}
					_, werr := f.WriteString(want.Args[2])
					if cerr := f.Close(); werr != nil || cerr != nil {
						t.Fatal(werr, cerr)
					}
					continue
				}
				args := make([]string, len(want.Args))
				for i, a := range want.Args {
					args[i] = strings.Replace(a, "H/", env.Home+"/", 1)
				}
				var out, errOut bytes.Buffer
				code := Run(args, nil, &out, &errOut, env)
				if code != want.Exit {
					t.Errorf("%v: exit %d, want %d\nstdout:\n%s\nstderr:\n%s", want.Args, code, want.Exit, out.String(), errOut.String())
				}
				if want.Stdout == nil {
					continue
				}
				if got := adoptNormalise(out.String(), env.Home); got != *want.Stdout {
					t.Errorf("%v stdout:\n got:\n%s\nwant:\n%s", want.Args, got, *want.Stdout)
				}
				if got := adoptNormalise(errOut.String(), env.Home); got != *want.Stderr {
					t.Errorf("%v stderr:\n got:\n%s\nwant:\n%s", want.Args, got, *want.Stderr)
				}
			}
			got := adoptSnapshot(t, env.Home)
			keys := map[string]bool{}
			for k := range got {
				keys[k] = true
			}
			for k := range v.Tree {
				keys[k] = true
			}
			var sorted []string
			for k := range keys {
				sorted = append(sorted, k)
			}
			sort.Strings(sorted)
			for _, k := range sorted {
				g, gok := got[k]
				w, wok := v.Tree[k]
				if gok != wok || g != w {
					t.Errorf("tree %s:\n got (%v) %q\nwant (%v) %q", k, gok, g, wok, w)
				}
			}
		})
	}
}
