package cli

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/mr-miles/aikito-go/internal/workspace"
)

// doctorfix_vectors.json is generated by testdata/gen_doctorfix_vectors.py
// from the reference CLI: `doctor --fix` runs (full output and exit code)
// and the agents/*.toml files they leave behind, covering the additive
// registry backfill (missing fields, missing tables, unregistered installed
// agents) and its idempotence.
func TestDoctorFixMatchesPython(t *testing.T) {
	data, err := os.ReadFile("testdata/doctorfix_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var scenarios map[string]struct {
		reportVector
		Agents map[string]string `json:"agents"`
	}
	if err := json.Unmarshal(data, &scenarios); err != nil {
		t.Fatal(err)
	}
	if isStdoutTTY() {
		t.Skip("doctor output depends on stdout not being a terminal")
	}
	saved := time.Local
	time.Local = time.UTC
	t.Cleanup(func() { time.Local = saved })
	t.Setenv("PATH", "/usr/bin:/bin")
	t.Setenv("TZ", "UTC")

	for name, sc := range scenarios {
		t.Run(name, func(t *testing.T) {
			home := resolvedTempDir(t)
			env := Environment{Home: home, Env: workspace.MapEnv{}, Cwd: home}
			applyReportSetup(t, env, sc.Setup)
			for _, c := range sc.Commands {
				var out, errOut bytes.Buffer
				code := Run(append([]string(nil), c.Args...), nil, &out, &errOut, env)
				norm := func(s string) string { return strings.ReplaceAll(s, home, "H") }
				label := strings.Join(c.Args, " ")
				if code != c.Exit {
					t.Errorf("%s: exit %d, want %d", label, code, c.Exit)
				}
				if got := norm(out.String()); got != c.Stdout {
					t.Errorf("%s: stdout differs\n--- got\n%s\n--- want\n%s", label, got, c.Stdout)
				}
				if got := norm(errOut.String()); got != c.Stderr {
					t.Errorf("%s: stderr differs\n--- got\n%s\n--- want\n%s", label, got, c.Stderr)
				}
			}
			matches, _ := filepath.Glob(filepath.Join(home, "aikito", "agents", "*.toml"))
			sort.Strings(matches)
			got := map[string]string{}
			for _, p := range matches {
				b, _ := os.ReadFile(p)
				got[filepath.Base(p)] = string(b)
			}
			for f, want := range sc.Agents {
				if got[f] != want {
					t.Errorf("agents/%s differs\n--- got\n%s\n--- want\n%s", f, got[f], want)
				}
			}
			if len(got) != len(sc.Agents) {
				t.Errorf("agent files: got %d, want %d", len(got), len(sc.Agents))
			}
		})
	}
}
