package cli

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"

	"github.com/mr-miles/aikito-go/internal/workspace"
)

// mcpLiveFixture serves the same MCP-over-HTTP responses as the fixture in
// testdata/gen_mcplive_vectors.py.
func mcpLiveFixture() http.Handler {
	pages := map[string]struct {
		names []string
		next  string
	}{"": {[]string{"alpha", "beta"}, "page-2"}, "page-2": {[]string{"gamma"}, ""}}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		reply := func(code int, body any) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(code)
			if body != nil {
				_ = json.NewEncoder(w).Encode(body)
			}
		}
		data, _ := io.ReadAll(r.Body)
		var msg map[string]any
		_ = json.Unmarshal(data, &msg)
		if r.URL.Path == "/broken" {
			reply(400, map[string]any{"error": map[string]any{"message": "bad fixture request"}})
			return
		}
		id, hasID := msg["id"]
		if !hasID {
			reply(202, nil)
			return
		}
		switch msg["method"] {
		case "initialize":
			result := map[string]any{"capabilities": map[string]any{}, "serverInfo": map[string]any{"name": "fixture", "version": "1"}}
			if r.URL.Path != "/noversion" {
				result["protocolVersion"] = "2025-06-18"
			}
			reply(200, map[string]any{"jsonrpc": "2.0", "id": id, "result": result})
		case "tools/list":
			cursor := ""
			if p, ok := msg["params"].(map[string]any); ok {
				cursor, _ = p["cursor"].(string)
			}
			page := pages[cursor]
			var tools []map[string]any
			for _, n := range page.names {
				tools = append(tools, map[string]any{"name": n})
			}
			result := map[string]any{"tools": tools}
			if page.next != "" {
				result["nextCursor"] = page.next
			}
			reply(200, map[string]any{"jsonrpc": "2.0", "id": id, "result": result})
		default:
			reply(200, map[string]any{"jsonrpc": "2.0", "id": id, "error": map[string]any{"code": -32601, "message": "no such method"}})
		}
	})
}

// mcplive_vectors.json is generated by testdata/gen_mcplive_vectors.py:
// `show mcp --live` (matrix, runtime table, tool list, errors) against a
// local fixture server, from the reference CLI.
func TestShowMCPLiveMatchesPython(t *testing.T) {
	data, err := os.ReadFile("testdata/mcplive_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var scenarios map[string]reportVector
	if err := json.Unmarshal(data, &scenarios); err != nil {
		t.Fatal(err)
	}
	if isStdoutTTY() {
		t.Skip("output depends on stdout not being a terminal")
	}
	t.Setenv("PATH", "/usr/bin:/bin")
	server := httptest.NewServer(mcpLiveFixture())
	defer server.Close()
	url := server.URL

	for name, sc := range scenarios {
		t.Run(name, func(t *testing.T) {
			home := resolvedTempDir(t)
			env := Environment{Home: home, Env: workspace.MapEnv{}, Cwd: home}
			for _, step := range sc.Setup {
				for i := range step {
					step[i] = strings.ReplaceAll(step[i], "{URL}", url)
				}
			}
			applyReportSetup(t, env, sc.Setup)
			for _, c := range sc.Commands {
				var out, errOut bytes.Buffer
				code := Run(append([]string(nil), c.Args...), nil, &out, &errOut, env)
				norm := func(s string) string {
					return strings.ReplaceAll(strings.ReplaceAll(s, home, "H"), url, "{URL}")
				}
				label := strings.Join(c.Args, " ")
				if code != c.Exit {
					t.Errorf("%s: exit %d, want %d", label, code, c.Exit)
				}
				if got := norm(out.String()); got != c.Stdout {
					t.Errorf("%s: stdout differs\n--- got\n%s\n--- want\n%s", label, got, c.Stdout)
				}
				if got := norm(errOut.String()); got != c.Stderr {
					t.Errorf("%s: stderr differs\n--- got\n%s\n--- want\n%s", label, got, c.Stderr)
				}
			}
		})
	}
}
