package cli

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/mr-miles/aikito-go/internal/projectsync"
)

// ../projectsync/testdata/recovery_vectors.json is generated by
// gen_recovery_vectors.py: the reference CLI's `sync project` hard-killed
// after each transaction-journal write (some states then tampered with), the
// resulting home saved as a relocatable fixture, and what the reference CLI's
// recovery then printed and left on disk. This recreates each fixture in a
// temp home and checks the Go CLI recovers (or refuses) identically.

type recoveryEntry struct {
	Path   string `json:"path"`
	Kind   string `json:"kind"`
	Blob   string `json:"blob"`
	Mode   uint32 `json:"mode"`
	Target string `json:"target"`
}

type recoveryHash struct {
	Hash string `json:"hash"`
	WS   string `json:"ws"`
	Proj string `json:"proj"`
	CO   string `json:"co"`
}

type recoveryCase struct {
	Fixture []recoveryEntry `json:"fixture"`
	Hashes  []recoveryHash  `json:"hashes"`
	Steps   []struct {
		Args   []string `json:"args"`
		Exit   int      `json:"exit"`
		Stdout string   `json:"stdout"`
		Stderr string   `json:"stderr"`
		Tree   []string `json:"tree"`
	} `json:"steps"`
}

var txidRe = regexp.MustCompile(`[0-9a-f]{32}`)

// relocate maps the fixture's {H} and binding hashes onto this home.
type relocate struct {
	home   string
	hashes [][2]string // old hash -> new hash
}

func (r relocate) apply(data []byte) []byte {
	data = bytes.ReplaceAll(data, []byte("{H}"), []byte(r.home))
	for _, h := range r.hashes {
		data = bytes.ReplaceAll(data, []byte(h[0]), []byte(h[1]))
	}
	return data
}

// jsonCharRe masks json.loads' "(char N)": an absolute offset into a file
// that embeds the home path, so it varies with the temp home's length.
var jsonCharRe = regexp.MustCompile(`\(char \d+\)`)

func (r relocate) normalize(data []byte) []byte {
	data = bytes.ReplaceAll(data, []byte(r.home), []byte("{H}"))
	for _, h := range r.hashes {
		data = bytes.ReplaceAll(data, []byte(h[1]), []byte("{BINDING}"))
	}
	return txidRe.ReplaceAll(data, []byte("TXID"))
}

func normalizeJSONChar(s string) string { return jsonCharRe.ReplaceAllString(s, "(char N)") }

func materializeRecoveryFixture(t *testing.T, c recoveryCase, blobs map[string]string, home string) relocate {
	t.Helper()
	r := relocate{home: home}
	for _, h := range c.Hashes {
		ws := strings.ReplaceAll(h.WS, "{H}", home)
		co := strings.ReplaceAll(h.CO, "{H}", home)
		r.hashes = append(r.hashes, [2]string{h.Hash, projectsync.BindingHash(ws, h.Proj, co)})
	}
	for _, e := range c.Fixture {
		path := filepath.Join(home, filepath.FromSlash(string(r.apply([]byte(e.Path)))))
		switch e.Kind {
		case "dir":
			if err := os.MkdirAll(path, os.FileMode(e.Mode)); err != nil {
				t.Fatal(err)
			}
			if err := os.Chmod(path, os.FileMode(e.Mode)); err != nil {
				t.Fatal(err)
			}
		case "link":
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(string(r.apply([]byte(e.Target))), path); err != nil {
				t.Fatal(err)
			}
		case "file":
			data, err := base64.StdEncoding.DecodeString(blobs[e.Blob])
			if err != nil {
				t.Fatal(err)
			}
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(path, r.apply(data), os.FileMode(e.Mode)); err != nil {
				t.Fatal(err)
			}
			if err := os.Chmod(path, os.FileMode(e.Mode)); err != nil {
				t.Fatal(err)
			}
		}
	}
	return r
}

// recoveryTree mirrors the generator's tree().
func recoveryTree(t *testing.T, r relocate) []string {
	t.Helper()
	home := r.home
	var lines []string
	err := filepath.WalkDir(home, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if p == home {
			return nil
		}
		if p == filepath.Join(home, "aikito", ".git") {
			return filepath.SkipDir
		}
		rel, _ := filepath.Rel(home, p)
		rel = string(r.normalize([]byte(filepath.ToSlash(rel))))
		info, err := os.Lstat(p)
		if err != nil {
			return err
		}
		switch {
		case info.Mode()&os.ModeSymlink != 0:
			target, _ := os.Readlink(p)
			lines = append(lines, fmt.Sprintf("L %s -> %s", rel, r.normalize([]byte(target))))
		case info.IsDir():
			lines = append(lines, "D "+rel)
		default:
			data, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			sum := sha256.Sum256(r.normalize(data))
			mode := ""
			if strings.HasPrefix(rel, ".local") {
				mode = fmt.Sprintf(" %o", info.Mode().Perm())
			}
			lines = append(lines, fmt.Sprintf("F %s%s %s", rel, mode, hex.EncodeToString(sum[:])[:16]))
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	sort.Strings(lines)
	return lines
}

func TestProjectSyncRecoveryMatchesPython(t *testing.T) {
	data, err := os.ReadFile("../projectsync/testdata/recovery_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var vectors struct {
		Blobs map[string]string       `json:"blobs"`
		Cases map[string]recoveryCase `json:"cases"`
	}
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatal(err)
	}
	names := make([]string, 0, len(vectors.Cases))
	for n := range vectors.Cases {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, name := range names {
		c := vectors.Cases[name]
		t.Run(name, func(t *testing.T) {
			env := testEnv(t)
			env.Cwd = env.Home
			r := materializeRecoveryFixture(t, c, vectors.Blobs, env.Home)
			for i, want := range c.Steps {
				var out, errOut bytes.Buffer
				code := Run(want.Args, nil, &out, &errOut, env)
				gotOut, gotErr := string(r.normalize(out.Bytes())), string(r.normalize(errOut.Bytes()))
				if code != want.Exit || normalizeJSONChar(gotOut) != normalizeJSONChar(want.Stdout) ||
					normalizeJSONChar(gotErr) != normalizeJSONChar(want.Stderr) {
					t.Errorf("step %d `aikito %s`:\n--- got exit %d\nstdout:\n%s\nstderr:\n%s\n--- want exit %d\nstdout:\n%s\nstderr:\n%s",
						i, strings.Join(want.Args, " "), code, gotOut, gotErr, want.Exit, want.Stdout, want.Stderr)
				}
				got := recoveryTree(t, r)
				if strings.Join(got, "\n") != strings.Join(want.Tree, "\n") {
					t.Errorf("step %d tree after `aikito %s`:\n--- got\n%s\n--- want\n%s",
						i, strings.Join(want.Args, " "), strings.Join(got, "\n"), strings.Join(want.Tree, "\n"))
				}
			}
		})
	}
}
