package cli

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/mr-miles/aikito-go/internal/workspace"
)

// report_vectors.json is generated by testdata/gen_report_vectors.py from
// the reference CLI: for each scenario, a setup script and the exact
// stdout/stderr/exit of the read-only report commands (status, doctor,
// show ...). The test replays the setup (CLI steps run in-process through
// this port) and requires byte-identical output, with the home directory
// written as "H".
//
// Known difference, filtered by the generator: doctor's "Interpreter
// consistent: <python>" finding, which only the Python CLI can produce.
type reportVector struct {
	Setup    [][]string `json:"setup"`
	Commands []struct {
		Args   []string `json:"args"`
		Stdout string   `json:"stdout"`
		Stderr string   `json:"stderr"`
		Exit   int      `json:"exit"`
	} `json:"commands"`
}

func applyReportSetup(t *testing.T, env Environment, steps [][]string) {
	t.Helper()
	home := env.Home
	for _, step := range steps {
		op, args := step[0], step[1:]
		for i := range args {
			args[i] = strings.ReplaceAll(args[i], "{H}", home)
		}
		switch op {
		case "cli":
			var out, errOut bytes.Buffer
			Run(args, nil, &out, &errOut, env)
		case "mkdir":
			if err := os.MkdirAll(filepath.Join(home, args[0]), 0o755); err != nil {
				t.Fatal(err)
			}
		case "write":
			p := filepath.Join(home, args[0])
			if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(p, []byte(args[1]), 0o644); err != nil {
				t.Fatal(err)
			}
		case "rm":
			if err := os.RemoveAll(filepath.Join(home, args[0])); err != nil {
				t.Fatal(err)
			}
		case "append":
			f, err := os.OpenFile(filepath.Join(home, args[0]), os.O_APPEND|os.O_WRONLY, 0)
			if err != nil {
				t.Fatal(err)
			}
			_, err = f.WriteString(args[1])
			f.Close()
			if err != nil {
				t.Fatal(err)
			}
		case "mtime":
			sec, _ := strconv.ParseInt(args[1], 10, 64)
			ts := time.Unix(sec, 0)
			if err := os.Chtimes(filepath.Join(home, args[0]), ts, ts); err != nil {
				t.Fatal(err)
			}
		case "edit_json":
			p := filepath.Join(home, args[0])
			data, err := os.ReadFile(p)
			if err != nil {
				t.Fatal(err)
			}
			var doc map[string]any
			if err := json.Unmarshal(data, &doc); err != nil {
				t.Fatal(err)
			}
			keys := strings.Split(args[1], ".")
			cur := doc
			for _, k := range keys[:len(keys)-1] {
				cur = cur[k].(map[string]any)
			}
			cur[keys[len(keys)-1]] = args[2]
			out, _ := json.MarshalIndent(doc, "", "  ")
			if err := os.WriteFile(p, append(out, '\n'), 0o644); err != nil {
				t.Fatal(err)
			}
		default:
			t.Fatalf("unknown setup op %q", op)
		}
	}
}

func TestReportCommandsMatchPython(t *testing.T) {
	data, err := os.ReadFile("testdata/report_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var scenarios map[string]reportVector
	if err := json.Unmarshal(data, &scenarios); err != nil {
		t.Fatal(err)
	}
	if isStdoutTTY() {
		t.Skip("report output depends on stdout not being a terminal")
	}
	// Inbox times are shown in local time; the vectors were made with TZ=UTC.
	saved := time.Local
	time.Local = time.UTC
	t.Cleanup(func() { time.Local = saved })
	t.Setenv("PATH", "/usr/bin:/bin")
	t.Setenv("TZ", "UTC")

	for name, sc := range scenarios {
		t.Run(name, func(t *testing.T) {
			home := resolvedTempDir(t)
			env := Environment{Home: home, Env: workspace.MapEnv{}, Cwd: home}
			applyReportSetup(t, env, sc.Setup)
			for _, c := range sc.Commands {
				args := append([]string(nil), c.Args...)
				cmdEnv := env
				if len(args) > 0 && strings.HasPrefix(args[0], "@cwd=") {
					cmdEnv.Cwd = filepath.Join(home, strings.TrimPrefix(args[0], "@cwd="))
					args = args[1:]
				}
				var out, errOut bytes.Buffer
				code := Run(args, nil, &out, &errOut, cmdEnv)
				norm := func(s string) string { return strings.ReplaceAll(s, home, "H") }
				label := strings.Join(c.Args, " ")
				if code != c.Exit {
					t.Errorf("%s: exit %d, want %d", label, code, c.Exit)
				}
				if got := norm(out.String()); got != c.Stdout {
					t.Errorf("%s: stdout differs\n--- got\n%s\n--- want\n%s", label, got, c.Stdout)
				}
				if got := norm(errOut.String()); got != c.Stderr {
					t.Errorf("%s: stderr differs\n--- got\n%s\n--- want\n%s", label, got, c.Stderr)
				}
			}
		})
	}
}
