package cli

import "testing"

// Golden vectors generated by invoking the real Python
// add.py._sanitize_mcp_url/_sanitize_mcp_headers directly.
func TestSanitizeMCPURL(t *testing.T) {
	cases := []struct {
		name     string
		url      string
		wantSafe string
		wantWarn int
	}{
		{"userinfo", "https://user:pass@example.com/mcp", "https://example.com/mcp", 1},
		{"sensitive_query", "https://example.com/mcp?api_key=SECRET123&foo=bar", "https://example.com/mcp?foo=bar", 1},
		{"token_and_safe_params", "https://example.com/mcp?token=abc&client_id=123&redirect_uri=https://x", "https://example.com/mcp?client_id=123&redirect_uri=https%3A%2F%2Fx", 1},
		{"userinfo_and_port_and_query", "https://user:pass@example.com:8443/mcp?password=xyz&normal=1", "https://example.com:8443/mcp?normal=1", 2},
		{"clean", "https://example.com/mcp", "https://example.com/mcp", 0},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			safe, warnings := SanitizeMCPURL(tc.url, "myserver")
			if safe != tc.wantSafe {
				t.Errorf("SanitizeMCPURL(%q) safe = %q, want %q", tc.url, safe, tc.wantSafe)
			}
			if len(warnings) != tc.wantWarn {
				t.Errorf("SanitizeMCPURL(%q) warnings = %d, want %d (%v)", tc.url, len(warnings), tc.wantWarn, warnings)
			}
		})
	}
}

func TestSanitizeMCPHeaders(t *testing.T) {
	headers := map[string]string{
		"Authorization": "Bearer abc123",
		"X-Custom":      "value",
		"Cookie":        "session=xyz",
		"X-Api-Key":     "${ENV_VAR}",
	}
	sanitized, warnings := SanitizeMCPHeaders(headers, "myserver")
	want := map[string]string{
		"Authorization": "${AIKITO_MYSERVER_AUTHORIZATION}",
		"X-Custom":      "value",
		"Cookie":        "${AIKITO_MYSERVER_COOKIE}",
		"X-Api-Key":     "${ENV_VAR}",
	}
	for k, v := range want {
		if sanitized[k] != v {
			t.Errorf("sanitized[%q] = %q, want %q", k, sanitized[k], v)
		}
	}
	if len(warnings) != 2 {
		t.Errorf("warnings = %d, want 2 (%v)", len(warnings), warnings)
	}
}
