package sync

import "testing"

// Golden vectors generated by invoking the real Python resource_kind_for_path
// directly across 23 representative paths.
func TestDefaultClassifier(t *testing.T) {
	cases := []struct {
		path        string
		inboxPrefix string
		wantKind    string
		wantOK      bool
	}{
		{"skills.toml", "", "skills-config", true},
		{"config.toml", "", "workspace-config", true},
		{"memory/foo.md", "", "memory", true},
		{"memory/foo.txt", "", "", false},
		{"skills/my-skill", "", "skill", true},
		{"skills/aikito", "", "", false},
		{"skills/durable-memory", "", "", false},
		{"agents/codex.toml", "", "agent", true},
		{"agents/codex.txt", "", "", false},
		{"subagents/my-sub.md", "", "subagent", true},
		{"mcps/my-server.toml", "", "mcp", true},
		{"global/AGENTS.md", "", "global-instructions", true},
		{"memory/notes/decision-1.md", "", "memory", true},
		{"memory/notes/Invalid Name.md", "", "", false},
		{"projects/myproj/agent.toml", "", "project-config", true},
		{"projects/myproj/AGENTS.md", "", "project-instructions", true},
		{"projects/myproj/memory/x.md", "", "memory", true},
		{"projects/myproj/memory/notes/y.md", "", "memory", true},
		{"projects/My.Proj/agent.toml", "", "project-config", true},
		{"inbox/note.md", "inbox", "inbox", true},
		{"inbox/sub/note.md", "inbox", "inbox", true},
		{"inbox/note.txt", "inbox", "", false},
		{"other/note.md", "inbox", "", false},
		{"random/path.txt", "", "", false},
	}
	for _, tc := range cases {
		t.Run(tc.path, func(t *testing.T) {
			kind, ok := DefaultClassifier(tc.path, tc.inboxPrefix)
			if ok != tc.wantOK || (ok && kind != tc.wantKind) {
				t.Errorf("DefaultClassifier(%q, %q) = (%q, %v), want (%q, %v)", tc.path, tc.inboxPrefix, kind, ok, tc.wantKind, tc.wantOK)
			}
		})
	}
}
