package sync

import "testing"

// strp is defined in transactions.go (package-level test+prod helper).

// Golden vectors generated by invoking the real Python
// aikito.workspace.merge.compare directly, not hand-derived.
func TestCompareGoldenVectors(t *testing.T) {
	cases := []struct {
		name   string
		base   map[string]struct{}
		local  *string
		remote *string
		want   Outcome
	}{
		{"both_missing_no_base", BaseSet(), nil, nil, Outcome{"NOOP", "", "Both sides agree"}},
		{"remote_created_no_base", BaseSet(), nil, strp("a"), Outcome{"CREATE", "local", "Remote changed"}},
		{"local_created_no_base", BaseSet(), strp("a"), nil, Outcome{"CREATE", "remote", "Local changed"}},
		{"both_equal_no_base", BaseSet(), strp("a"), strp("a"), Outcome{"NOOP", "", "Both sides agree"}},
		{"both_differ_no_base", BaseSet(), strp("a"), strp("b"), Outcome{"CONFLICT", "", "Both sides changed"}},
		{"both_unmodified", BaseSet("a"), strp("a"), strp("a"), Outcome{"NOOP", "", "Both sides agree"}},
		{"remote_changed", BaseSet("a"), strp("a"), strp("b"), Outcome{"UPDATE", "local", "Remote changed"}},
		{"local_changed", BaseSet("a"), strp("b"), strp("a"), Outcome{"UPDATE", "remote", "Local changed"}},
		{"both_changed_differently", BaseSet("a"), strp("b"), strp("c"), Outcome{"CONFLICT", "", "Both sides changed"}},
		{"local_deleted", BaseSet("a"), nil, strp("a"), Outcome{"DELETE", "remote", "Local changed"}},
		{"remote_deleted", BaseSet("a"), strp("a"), nil, Outcome{"DELETE", "local", "Remote changed"}},
		{"multi_fingerprint_base_unmodified", BaseSet("a", "b"), strp("a"), strp("b"), Outcome{"NOOP", "", "Both sides are unmodified"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := Compare(tc.base, tc.local, tc.remote)
			if got != tc.want {
				t.Errorf("Compare(%v, %v, %v) = %+v, want %+v", tc.base, tc.local, tc.remote, got, tc.want)
			}
		})
	}
}
