package sync

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mr-miles/aikito-go/internal/registry"
)

func writeFileT(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// setupSubagentFixture builds a minimal workspace with claude-code (per_file)
// and dsh (shared_patch) agent definitions, plus one subagent targeting
// both, exercising both adapter layouts.
func setupSubagentFixture(t *testing.T) (aikitoDir, home string) {
	t.Helper()
	home = t.TempDir()
	aikitoDir = filepath.Join(home, "aikito")
	writeFileT(t, filepath.Join(aikitoDir, "layout.toml"), "version = 2\n")
	for _, d := range []string{"agents", "subagents", "mcps", "skills", "memory/notes", "global", "projects"} {
		if err := os.MkdirAll(filepath.Join(aikitoDir, d), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	claudeTemplate, err := registry.BundledAgentTemplateText("claude-code")
	if err != nil {
		t.Fatal(err)
	}
	dshTemplate, err := registry.BundledAgentTemplateText("dsh")
	if err != nil {
		t.Fatal(err)
	}
	writeFileT(t, filepath.Join(aikitoDir, "agents", "claude-code.toml"), claudeTemplate)
	writeFileT(t, filepath.Join(aikitoDir, "agents", "dsh.toml"), dshTemplate)
	// Deterministic detection: marker directories, no reliance on real PATH.
	if err := os.MkdirAll(filepath.Join(home, ".claude"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(home, ".dsh"), 0o755); err != nil {
		t.Fatal(err)
	}
	writeFileT(t, filepath.Join(aikitoDir, "subagents", "reviewer.md"),
		"---\ndescription: \"Reviews code changes for correctness\"\nagents: [\"claude-code\", \"dsh\"]\n---\n"+
			"Review the diff carefully. Look for bugs, security issues, and style problems.\n")
	return aikitoDir, home
}

// Cross-validated against the real Python `aikito sync subagents` (dry-run,
// apply, NOOP re-run, conflict, --force) via subprocess+file diff during
// manual testing (including the per_file claude-code target and the
// shared_patch dsh cordis.patch.yml target) — this test locks in the same
// scenarios in-process.
func TestBuildAndApplySubagentPlanCreateThenNoop(t *testing.T) {
	aikitoDir, home := setupSubagentFixture(t)

	ops, err := BuildSubagentPlan(aikitoDir, home, BuildSubagentPlanOptions{GateInstalled: true})
	if err != nil {
		t.Fatal(err)
	}
	var creates int
	for _, op := range ops {
		if op.Subagent == "reviewer" {
			if op.Action != SACreate {
				t.Errorf("op for %s/%s = %s, want CREATE", op.Agent, op.Subagent, op.Action)
			}
			creates++
			if _, err := ApplySubagentPlan([]SubagentOperation{op}, home); err != nil {
				t.Fatal(err)
			}
		}
	}
	if creates != 2 {
		t.Fatalf("expected 2 CREATE ops (claude-code, dsh), got %d", creates)
	}

	claudeTarget := filepath.Join(home, ".claude", "agents", "reviewer.md")
	data, err := os.ReadFile(claudeTarget)
	if err != nil {
		t.Fatal(err)
	}
	if strings.HasSuffix(string(data), "\n\n") {
		t.Errorf("rendered claude markdown has a double trailing newline: %q", data)
	}
	if !strings.Contains(string(data), "generated by aikito from subagents/reviewer.md") {
		t.Errorf("rendered claude markdown missing the aikito marker: %q", data)
	}

	dshTarget := filepath.Join(home, ".dsh", "cordis.patch.yml")
	dshData, err := os.ReadFile(dshTarget)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(dshData), "aikito-subagent-reviewer") {
		t.Errorf("cordis.patch.yml missing the expected item id: %q", dshData)
	}

	// Re-run: everything should now be NOOP.
	ops2, err := BuildSubagentPlan(aikitoDir, home, BuildSubagentPlanOptions{GateInstalled: true})
	if err != nil {
		t.Fatal(err)
	}
	for _, op := range ops2 {
		if op.Subagent == "reviewer" && op.Action != SANoop {
			t.Errorf("re-run op for %s/%s = %s, want NOOP", op.Agent, op.Subagent, op.Action)
		}
	}
}

func TestBuildSubagentPlanConflictAndForce(t *testing.T) {
	aikitoDir, home := setupSubagentFixture(t)
	ops, err := BuildSubagentPlan(aikitoDir, home, BuildSubagentPlanOptions{GateInstalled: true})
	if err != nil {
		t.Fatal(err)
	}
	for _, op := range ops {
		if op.Subagent == "reviewer" && op.Action == SACreate {
			if _, err := ApplySubagentPlan([]SubagentOperation{op}, home); err != nil {
				t.Fatal(err)
			}
		}
	}

	// Hand-edit the claude-code target to break the marker.
	claudeTarget := filepath.Join(home, ".claude", "agents", "reviewer.md")
	writeFileT(t, claudeTarget, "unmanaged content\n")

	opsConflict, err := BuildSubagentPlan(aikitoDir, home, BuildSubagentPlanOptions{GateInstalled: true})
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, op := range opsConflict {
		if op.Agent == "claude-code" && op.Subagent == "reviewer" {
			found = true
			if op.Action != SAConflict || op.IsAuthorized {
				t.Errorf("expected an unauthorized CONFLICT, got action=%s authorized=%v", op.Action, op.IsAuthorized)
			}
		}
	}
	if !found {
		t.Fatal("expected a claude-code/reviewer operation")
	}

	// --force claude-code/reviewer: CONFLICT -> authorized UPDATE.
	opsForced, err := BuildSubagentPlan(aikitoDir, home, BuildSubagentPlanOptions{
		GateInstalled: true, ForceTargets: []string{"claude-code/reviewer"},
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, op := range opsForced {
		if op.Agent == "claude-code" && op.Subagent == "reviewer" {
			if op.Action != SAUpdate || !op.IsAuthorized || !op.RequiresForce {
				t.Errorf("expected an authorized force UPDATE, got action=%s authorized=%v requiresForce=%v",
					op.Action, op.IsAuthorized, op.RequiresForce)
			}
			if _, err := ApplySubagentPlan([]SubagentOperation{op}, home); err != nil {
				t.Fatal(err)
			}
		}
	}
	data, _ := os.ReadFile(claudeTarget)
	if strings.Contains(string(data), "unmanaged content") {
		t.Error("--force did not overwrite the unmanaged content")
	}
}

func TestBuildSubagentPlanBareForceRejected(t *testing.T) {
	aikitoDir, home := setupSubagentFixture(t)
	_, err := BuildSubagentPlan(aikitoDir, home, BuildSubagentPlanOptions{
		GateInstalled: true, ForceTargets: []string{},
	})
	if err == nil {
		t.Fatal("expected an error for bare --force with no explicit targets")
	}
	if !strings.Contains(err.Error(), "requires explicit") {
		t.Errorf("unexpected error message: %v", err)
	}
}

func TestBuildSubagentPlanUnknownAgentIsHardError(t *testing.T) {
	aikitoDir, home := setupSubagentFixture(t)
	writeFileT(t, filepath.Join(aikitoDir, "subagents", "broken.md"),
		"---\ndescription: \"x\"\nagents: [\"codex\"]\n---\nBody.\n")
	_, err := BuildSubagentPlan(aikitoDir, home, BuildSubagentPlanOptions{GateInstalled: true})
	if err == nil {
		t.Fatal("expected a hard error for a subagent referencing an agent with no subagents config")
	}
	if !strings.Contains(err.Error(), "no [agents.codex.subagents] configuration") {
		t.Errorf("unexpected error message: %v", err)
	}
}
