// Subagent synchronization: render each canonical subagents/<name>.md into
// every targeted agent's native format and compare against the actual
// on-disk state. Ported from aikito/src/aikito/subagent.py's
// build_subagent_plan/sync_subagent_configs DECISION LOGIC — not from its
// types, which are built on config_runtime.py's unported ConfigTarget/
// ConfigOperation framework. This file re-implements the same decisions
// directly against this Go port's existing primitives (internal/subagent's
// adapters, internal/registry's AgentDefinition).
//
// Conflict detection here is NOT a persisted-fingerprint state file (unlike
// internal/mcp/state.go) — Python embeds a literal marker comment
// ("generated by aikito from subagents/<name>.md ...") in every rendered
// subagent file/block, and treats its ABSENCE on an existing target as
// "this was hand-authored, don't overwrite without --force". This Go port
// reuses that same marker (internal/subagent.HasAikitoMarker/
// HasAikitoMarkerText, already built), so no separate state file is needed.
package sync

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/mr-miles/aikito-go/internal/registry"
	"github.com/mr-miles/aikito-go/internal/subagent"
	"github.com/mr-miles/aikito-go/internal/workspace"
)

// SubagentConfigError mirrors subagent.py's SubagentConfigError.
type SubagentConfigError struct{ Message string }

func (e *SubagentConfigError) Error() string { return e.Message }

func subagentErrorf(format string, args ...any) error {
	return &SubagentConfigError{Message: fmt.Sprintf(format, args...)}
}

type SubagentOpAction string

const (
	SACreate   SubagentOpAction = "CREATE"
	SAUpdate   SubagentOpAction = "UPDATE"
	SANoop     SubagentOpAction = "NOOP"
	SAConflict SubagentOpAction = "CONFLICT"
	SASkip     SubagentOpAction = "SKIP"
	SAError    SubagentOpAction = "ERROR"
	SARemove   SubagentOpAction = "REMOVE"
	SAOrphan   SubagentOpAction = "ORPHAN"
)

// SubagentOperation is one planned action against one (agent, subagent)
// pair (or an agent-wide SKIP, logical identity "*").
type SubagentOperation struct {
	Agent           string
	Subagent        string // logical identity; "*" for an agent-wide SKIP
	TargetPath      string // physical file (shared for every shared_patch subagent on one agent)
	Layout          subagent.Layout
	Action          SubagentOpAction
	Reason          string
	RequiresForce   bool
	IsAuthorized    bool
	RenderedPayload string // desired content, for CREATE/UPDATE
	// PreImage is the target file as it was when the plan was built
	// (aggregate_file_plans' pre_image); the executor refuses to write if
	// it changed since.
	PreImage *FileSnapshot
}

// BuildSubagentPlanOptions mirrors build_subagent_plan's keyword args.
type BuildSubagentPlanOptions struct {
	// ForceTargets: nil = no forcing. Non-nil-but-empty mirrors Python's
	// argparse nargs="*" bare `--force` with no values, which is REJECTED
	// (subagent force is always per-target, "<agent>/<subagent>", never a
	// blanket boolean like `sync mcp`'s --force) — BuildSubagentPlan
	// returns a *SubagentConfigError in that case, matching Python exactly.
	ForceTargets []string
	Prune        bool
	// GateInstalled defaults to true in Python; exposed for completeness,
	// always pass true from the CLI layer.
	GateInstalled bool
}

func normalizeForceTargets(forceTargets []string) (map[string]bool, error) {
	authorized := map[string]bool{}
	if forceTargets == nil {
		return authorized, nil
	}
	if len(forceTargets) == 0 {
		return nil, subagentErrorf("--force requires explicit <agent>/<subagent> target(s), e.g. --force claude-code/verifier")
	}
	for _, ft := range forceTargets {
		parts := strings.Split(ft, "/")
		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
			return nil, subagentErrorf("Invalid --force target '%s'. Must be in format <agent>/<subagent>", ft)
		}
		authorized[strings.TrimSpace(ft)] = true
	}
	return authorized, nil
}

// subagentNamePattern is subagent.py's SUBAGENT_NAME_PATTERN.
var subagentNamePattern = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)

// loadSubagentDefinitions ports subagent.py's load_subagent_definitions:
// every entry under subagents/ must be a <name>.md with a valid name, apart
// from OS clutter files.
func loadSubagentDefinitions(aikitoDir string) (map[string]subagent.Definition, error) {
	dir := filepath.Join(aikitoDir, "subagents")
	if fi, err := os.Lstat(dir); err != nil || !fi.IsDir() {
		return nil, subagentErrorf("Subagents directory missing or unsafe: %s", dir)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	defs := map[string]subagent.Definition{}
	for _, e := range entries {
		name := e.Name()
		switch name {
		case ".DS_Store", "Thumbs.db", "desktop.ini":
			continue
		}
		subName := strings.TrimSuffix(name, ".md")
		if !strings.HasSuffix(name, ".md") || !subagentNamePattern.MatchString(subName) {
			return nil, subagentErrorf("Unsupported subagent entry: %s", filepath.Join(dir, name))
		}
		metadata, body, err := workspace.ParseSubagentFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		desc, _ := metadata["description"].(string)
		var agentNames []string
		if raw, ok := metadata["agents"].([]any); ok {
			for _, a := range raw {
				if s, ok := a.(string); ok {
					agentNames = append(agentNames, s)
				}
			}
		}
		platformConfigs := map[string]map[string]any{}
		for k, v := range metadata {
			if k == "description" || k == "agents" {
				continue
			}
			if m, ok := v.(map[string]any); ok {
				platformConfigs[k] = m
			}
		}
		defs[subName] = subagent.Definition{
			Name: subName, Description: desc, Agents: agentNames,
			// subagent.py's load_subagent_definitions does
			// instructions=body.strip() before storing it — found via
			// cross-validation against live Python (an earlier version of
			// this loader didn't strip, producing a double trailing
			// newline in every per_file rendered output, since the
			// render functions' own "\n".join([..., instructions, ""])
			// already supplies the single trailing newline).
			PlatformConfigs: platformConfigs, Instructions: strings.TrimSpace(body),
		}
	}
	return defs, nil
}

// renderSubagent mirrors subagent.py's render_subagent: validate the
// agent-specific platform options, normalize instruction line endings, then
// render through the platform adapter.
func renderSubagent(def subagent.Definition, agentName string, adapter subagent.Adapter) (string, error) {
	rawOpts := def.PlatformConfigs[agentName]
	if rawOpts == nil {
		rawOpts = map[string]any{}
	}
	options, err := adapter.ValidateOptions(agentName, def.Name, rawOpts)
	if err != nil {
		return "", err
	}
	instructions := strings.ReplaceAll(def.Instructions, "\r\n", "\n")
	instructions = strings.ReplaceAll(instructions, "\r", "\n")
	return adapter.Render(def.Name, def.Description, options, instructions)
}

// BuildSubagentPlan mirrors build_subagent_plan.
func BuildSubagentPlan(aikitoDir, home string, opts BuildSubagentPlanOptions) ([]SubagentOperation, error) {
	authorizedForce, err := normalizeForceTargets(opts.ForceTargets)
	if err != nil {
		return nil, err
	}

	allDefs, err := registry.LoadAgentDefinitions(aikitoDir, home)
	if err != nil {
		return nil, err
	}
	subagentConfigs := map[string]registry.AgentDefinition{}
	for name, d := range allDefs {
		if d.Subagents != nil {
			subagentConfigs[name] = d
		}
	}

	subagentDefs, err := loadSubagentDefinitions(aikitoDir)
	if err != nil {
		return nil, err
	}
	// load_subagent_definitions validates every platform table that names a
	// known agent while loading, so one bad field fails the whole plan.
	for _, subName := range sortedSubagentNames(subagentDefs) {
		def := subagentDefs[subName]
		platforms := make([]string, 0, len(def.PlatformConfigs))
		for p := range def.PlatformConfigs {
			platforms = append(platforms, p)
		}
		sort.Strings(platforms)
		for _, p := range platforms {
			agentDef, known := allDefs[p]
			if !known {
				continue
			}
			if agentDef.Subagents == nil {
				return nil, subagentErrorf("Subagent '%s' platform '%s' has no defined subagents capability", subName, p)
			}
			adapter, aerr := subagent.GetSubagentAdapter(agentDef.Subagents.ConfigFormat)
			if aerr != nil {
				return nil, aerr
			}
			if _, verr := adapter.ValidateOptions(p, subName, def.PlatformConfigs[p]); verr != nil {
				return nil, verr
			}
		}
	}

	// Hard error (not a skip) if any subagent targets a registered-or-not
	// agent with no [agents.<name>.subagents] section at all.
	for subName, def := range subagentDefs {
		for _, agentName := range def.Agents {
			if _, ok := subagentConfigs[agentName]; !ok {
				return nil, subagentErrorf(
					"Subagent '%s' targets agent '%s', but '%s' has no [agents.%s.subagents] configuration in agents/<name>.toml",
					subName, agentName, agentName, agentName)
			}
		}
	}

	var ops []SubagentOperation

	// Agents with no subagents section at all: one agent-wide SKIP each,
	// purely informational (nothing targets them, or the hard error above
	// would have already fired).
	allAgentNames := make([]string, 0, len(allDefs))
	for name := range allDefs {
		allAgentNames = append(allAgentNames, name)
	}
	sort.Strings(allAgentNames)
	for _, agentName := range allAgentNames {
		if _, ok := subagentConfigs[agentName]; !ok {
			ops = append(ops, SubagentOperation{
				Agent: agentName, Subagent: "*", Action: SASkip,
				Reason: "Agent has no subagents section in agents/<name>.toml",
			})
		}
	}

	agentNames := make([]string, 0, len(subagentConfigs))
	for name := range subagentConfigs {
		agentNames = append(agentNames, name)
	}
	sort.Strings(agentNames)

	for _, agentName := range agentNames {
		agentDef := subagentConfigs[agentName]
		subCap := agentDef.Subagents
		adapter, aerr := subagent.GetSubagentAdapter(subCap.ConfigFormat)
		if aerr != nil {
			ops = append(ops, SubagentOperation{
				Agent: agentName, Subagent: "*", Action: SAError,
				Reason: aerr.Error(), IsAuthorized: false,
			})
			continue
		}

		if opts.GateInstalled {
			installed := registry.IsAgentInstalled(agentDef.Agent, home, nil)
			if installed != nil && !*installed {
				hasSubagents := false
				for _, subName := range sortedSubagentNames(subagentDefs) {
					def := subagentDefs[subName]
					if !containsStr(def.Agents, agentName) {
						continue
					}
					hasSubagents = true
					targetPath := adapter.ResolveTargetPath(subCap.ConfigPath, subName)
					ops = append(ops, SubagentOperation{
						Agent: agentName, Subagent: subName, TargetPath: targetPath, Layout: adapter.Layout,
						Action: SASkip, Reason: fmt.Sprintf("Agent '%s' is not installed on this host", agentName),
					})
				}
				if !hasSubagents {
					ops = append(ops, SubagentOperation{
						Agent: agentName, Subagent: "*", TargetPath: subCap.ConfigPath, Layout: adapter.Layout,
						Action: SASkip, Reason: fmt.Sprintf("Agent '%s' is not installed on this host", agentName),
					})
				}
				continue
			}
		}

		if subCap.RequiresPath != nil {
			if _, err := os.Stat(*subCap.RequiresPath); err != nil {
				ops = append(ops, SubagentOperation{
					Agent: agentName, Subagent: "*", TargetPath: subCap.ConfigPath, Layout: adapter.Layout,
					Action: SASkip, Reason: fmt.Sprintf("Optional subagent capability is not installed at %s", *subCap.RequiresPath),
				})
				continue
			}
		}

		if adapter.AvailabilityCheck != nil {
			enabled, msg, cerr := adapter.AvailabilityCheck(subCap.ConfigPath)
			if cerr == nil && !enabled {
				ops = append(ops, SubagentOperation{
					Agent: agentName, Subagent: "*", TargetPath: subCap.ConfigPath, Layout: adapter.Layout,
					Action: SAError, Reason: msg, IsAuthorized: false,
				})
			}
		}

		defined := map[string]bool{}

		if adapter.Layout == subagent.LayoutSharedPatch {
			patchText := ""
			if data, err := os.ReadFile(subCap.ConfigPath); err == nil {
				patchText = string(data)
			}
			for _, subName := range sortedSubagentNames(subagentDefs) {
				def := subagentDefs[subName]
				if !containsStr(def.Agents, agentName) {
					continue
				}
				defined[subName] = true
				op := SubagentOperation{Agent: agentName, Subagent: subName, TargetPath: subCap.ConfigPath, Layout: adapter.Layout}

				rendered, rerr := renderSubagent(def, agentName, adapter)
				if rerr != nil {
					op.Action, op.Reason = SAError, rerr.Error()
					ops = append(ops, op)
					continue
				}
				op.RenderedPayload = rendered

				forceID := agentName + "/" + subName
				isForceAuth := authorizedForce[forceID]

				existingBlock, exists := adapter.ReadItem(patchText, subName)
				switch {
				case !exists:
					op.Action, op.Reason = SACreate, "Subagent plugin item does not exist in cordis.patch.yml"
				case subagent.HasAikitoMarkerText(existingBlock):
					if strings.TrimSpace(existingBlock) == strings.TrimSpace(rendered) {
						op.Action, op.Reason = SANoop, "Up to date"
					} else {
						op.Action, op.Reason = SAUpdate, "Subagent configuration changed in cordis.patch.yml"
					}
				default:
					op.Reason = "Target plugin item exists without Aikito marker"
					op.RequiresForce = true
					if isForceAuth {
						op.Action, op.IsAuthorized = SAUpdate, true
					} else {
						op.Action = SAConflict
					}
				}
				if op.Action == SACreate || op.Action == SAUpdate || op.Action == SANoop {
					op.IsAuthorized = true
				}
				ops = append(ops, op)
			}

			for _, managedName := range sortedKeysOf(mustManaged(adapter, subCap.ConfigPath)) {
				if defined[managedName] {
					continue
				}
				action := SAOrphan
				if opts.Prune {
					action = SARemove
				}
				ops = append(ops, SubagentOperation{
					Agent: agentName, Subagent: managedName, TargetPath: subCap.ConfigPath, Layout: adapter.Layout,
					Action: action, Reason: "Managed subagent in cordis.patch.yml is no longer defined in subagents/<name>.toml",
					RequiresForce: true, IsAuthorized: opts.Prune,
				})
			}
			continue
		}

		for _, subName := range sortedSubagentNames(subagentDefs) {
			def := subagentDefs[subName]
			if !containsStr(def.Agents, agentName) {
				continue
			}
			defined[subName] = true
			targetPath := adapter.ResolveTargetPath(subCap.ConfigPath, subName)
			op := SubagentOperation{Agent: agentName, Subagent: subName, TargetPath: targetPath, Layout: adapter.Layout}

			rendered, rerr := renderSubagent(def, agentName, adapter)
			if rerr != nil {
				op.Action, op.Reason = SAError, rerr.Error()
				ops = append(ops, op)
				continue
			}
			op.RenderedPayload = rendered

			forceID := agentName + "/" + subName
			isForceAuth := authorizedForce[forceID]

			if _, err := os.Stat(targetPath); err != nil {
				op.Action, op.Reason, op.IsAuthorized = SACreate, "Target file does not exist", true
			} else if subagent.HasAikitoMarker(targetPath) {
				data, _ := os.ReadFile(targetPath)
				current := normalizeNewlines(string(data))
				if current == normalizeNewlines(rendered) {
					op.Action, op.Reason, op.IsAuthorized = SANoop, "Up to date", true
				} else {
					op.Action, op.Reason, op.IsAuthorized = SAUpdate, "Content changed", true
				}
			} else {
				op.Reason = "Target file exists without Aikito marker"
				op.RequiresForce = true
				if isForceAuth {
					op.Action, op.IsAuthorized = SAUpdate, true
				} else {
					op.Action = SAConflict
				}
			}
			ops = append(ops, op)
		}

		managed, _ := adapter.ListManaged(subCap.ConfigPath)
		for _, subName := range sortedKeysOf(managed) {
			if defined[subName] {
				continue
			}
			action := SAOrphan
			if opts.Prune {
				action = SARemove
			}
			ops = append(ops, SubagentOperation{
				Agent: agentName, Subagent: subName, TargetPath: managed[subName], Layout: adapter.Layout,
				Action: action, Reason: "Managed subagent is no longer defined in subagents/<name>.toml",
				RequiresForce: true, IsAuthorized: opts.Prune,
			})
		}
	}

	snapshots := map[string]*FileSnapshot{}
	for i := range ops {
		if ops[i].TargetPath == "" || ops[i].Action == SASkip {
			continue
		}
		snap, ok := snapshots[ops[i].TargetPath]
		if !ok {
			captured := CaptureFileSnapshot(ops[i].TargetPath)
			snap = &captured
			snapshots[ops[i].TargetPath] = snap
		}
		ops[i].PreImage = snap
	}
	return ops, nil
}

func writeFileEnsureDir(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o777); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func normalizeNewlines(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	return strings.ReplaceAll(s, "\r", "\n")
}

func containsStr(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

// sortedSubagentNames returns subagentDefs' keys in sorted order, for
// deterministic iteration (matching Python's sorted(subagent_defs.keys())).
func sortedSubagentNames(defs map[string]subagent.Definition) []string {
	names := make([]string, 0, len(defs))
	for n := range defs {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func sortedKeysOf(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func mustManaged(adapter subagent.Adapter, configPath string) map[string]string {
	m, err := adapter.ListManaged(configPath)
	if err != nil {
		return map[string]string{}
	}
	return m
}
