package subagent

import (
	"encoding/json"
	"os"
	"testing"
)

type goldenCase struct {
	OK    bool   `json:"ok"`
	Value string `json:"value"`
	Error string `json:"error"`
}

func loadGolden(t *testing.T) map[string]goldenCase {
	t.Helper()
	data, err := os.ReadFile("testdata/render_golden.json")
	if err != nil {
		t.Fatal(err)
	}
	var out map[string]goldenCase
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatal(err)
	}
	return out
}

// Every case below was generated by invoking the real Python
// subagent_adapters.py render_* functions directly (see
// testdata/render_golden.json's provenance script), not hand-derived.
func TestRenderFunctionsAgainstPython(t *testing.T) {
	golden := loadGolden(t)

	check := func(name string, got string, err error) {
		t.Helper()
		g, ok := golden[name]
		if !ok {
			t.Fatalf("no golden case named %q", name)
		}
		if !g.OK {
			if err == nil {
				t.Fatalf("expected an error matching %q, got none", g.Error)
			}
			return
		}
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got != g.Value {
			t.Errorf("%s mismatch:\n got:  %q\n want: %q", name, got, g.Value)
		}
	}

	t.Run("copilot_basic", func(t *testing.T) {
		got, err := RenderCopilotMarkdown("reviewer", "Reviews code",
			map[string]any{"model": "gpt-4", "tools": []any{"read", "write"}}, "You review code.\n")
		check("copilot_basic", got, err)
	})
	t.Run("copilot_with_name", func(t *testing.T) {
		got, err := RenderCopilotMarkdown("reviewer", "Reviews code",
			map[string]any{"name": "custom-name", "disable-model-invocation": true}, "Body.\n")
		check("copilot_with_name", got, err)
	})
	t.Run("claude_basic", func(t *testing.T) {
		got, err := RenderClaudeMarkdown("reviewer", "Reviews code",
			map[string]any{"model": "opus", "effort": "high"}, "You review code.\n")
		check("claude_basic", got, err)
	})
	t.Run("claude_empty_opts", func(t *testing.T) {
		got, err := RenderClaudeMarkdown("reviewer", "Reviews code", map[string]any{}, "Body.\n")
		check("claude_empty_opts", got, err)
	})
	t.Run("opencode_basic", func(t *testing.T) {
		got, err := RenderOpencodeMarkdown("reviewer", "Reviews code", map[string]any{"model": "gpt-4"}, "Body.\n")
		check("opencode_basic", got, err)
	})
	t.Run("grok_basic", func(t *testing.T) {
		got, err := RenderGrokMarkdown("reviewer", "Reviews code",
			map[string]any{"model": "x", "tools": []any{"a", "b"}, "agents_md": true}, "Body.\n")
		check("grok_basic", got, err)
	})
	t.Run("pi_both", func(t *testing.T) {
		got, err := RenderPiMarkdown("reviewer", "Reviews code",
			map[string]any{"model": "x", "tools": []any{"a"}}, "Body.\n")
		check("pi_both", got, err)
	})
	t.Run("pi_neither", func(t *testing.T) {
		got, err := RenderPiMarkdown("reviewer", "Reviews code", map[string]any{}, "Body.\n")
		check("pi_neither", got, err)
	})
	t.Run("agy_basic", func(t *testing.T) {
		got, err := RenderAgyMarkdown("reviewer", "Reviews code",
			map[string]any{"tools": []any{"a"}, "model": "x"}, "Body.\n")
		check("agy_basic", got, err)
	})
	t.Run("codex_basic", func(t *testing.T) {
		got, err := RenderCodexTOML("reviewer", "Reviews code",
			map[string]any{"model": "o3", "model_reasoning_effort": "high"}, "Line1\nLine2\n")
		check("codex_basic", got, err)
	})
	t.Run("codex_triple_quote_reject", func(t *testing.T) {
		_, err := RenderCodexTOML("x", "d", map[string]any{}, "has ''' in it")
		if err == nil {
			t.Fatal("expected an error for triple-single-quote instructions")
		}
	})
	t.Run("dsh_minimal", func(t *testing.T) {
		got, err := RenderDSHCordisSubagent("reviewer", "d", map[string]any{}, "Line1\nLine2\n")
		check("dsh_minimal", got, err)
	})
	t.Run("dsh_full", func(t *testing.T) {
		got, err := RenderDSHCordisSubagent("reviewer", "d", map[string]any{
			"provider": "custom", "model": "x", "maxTokens": int64(4000),
			"backgroundMode": "one-shot", "tools": []any{"a", "b"},
		}, "Line1\n\nLine3\n")
		check("dsh_full", got, err)
	})
}
