package subagent

import (
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"
)

func loadCordisGolden(t *testing.T) map[string]any {
	t.Helper()
	data, err := os.ReadFile("testdata/cordis_golden.json")
	if err != nil {
		t.Fatal(err)
	}
	var out map[string]any
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatal(err)
	}
	return out
}

const cordisMarker = "generated by aikito from subagents/reviewer.md - edits will be overwritten"

var item1 = "- id: aikito-subagent-reviewer\n  # " + cordisMarker + "\n  name: '@deepseek-ai/dsh-tool-subagent'\n  config:\n    provider: spawn\n    toolName: reviewer\n    persona: |-\n      Hello\n"

const item2Legacy = "- name: '@deepseek-ai/dsh-tool-subagent'\n  config:\n    toolName: writer\n    persona: |-\n      Write things\n"

const otherPlugin = "- id: some-other-plugin\n  name: 'other-plugin'\n  config:\n    foo: bar\n"

// Every expected value here was generated by running the real Python
// get/update/remove_dsh_cordis_subagent functions directly against the same
// fixture text (see testdata/cordis_golden.json's provenance script).
func TestDSHCordisEngineAgainstPython(t *testing.T) {
	golden := loadCordisGolden(t)

	wantStr := func(key string) string {
		v, ok := golden[key]
		if !ok || v == nil {
			return ""
		}
		return v.(string)
	}
	wantNil := func(key string) bool {
		v, ok := golden[key]
		return ok && v == nil
	}

	t.Run("get_empty", func(t *testing.T) {
		_, ok := GetDSHCordisSubagentItem("", "reviewer")
		if ok || !wantNil("get_empty") {
			t.Fatalf("expected absent, got ok=%v", ok)
		}
	})
	t.Run("get_all_empty", func(t *testing.T) {
		got := GetAllDSHCordisSubagents("")
		if len(got) != 0 {
			t.Fatalf("got %v, want empty", got)
		}
	})
	t.Run("update_empty", func(t *testing.T) {
		got := UpdateDSHCordisSubagent("", "reviewer", trimTrailingNewline(item1))
		if got != wantStr("update_empty") {
			t.Errorf("got %q want %q", got, wantStr("update_empty"))
		}
	})
	t.Run("remove_empty", func(t *testing.T) {
		got := RemoveDSHCordisSubagent("", "reviewer")
		if got != wantStr("remove_empty") {
			t.Errorf("got %q want %q", got, wantStr("remove_empty"))
		}
	})
	t.Run("get_by_id", func(t *testing.T) {
		got, ok := GetDSHCordisSubagentItem(item1, "reviewer")
		if !ok || got != wantStr("get_by_id") {
			t.Errorf("got (%v,%q) want %q", ok, got, wantStr("get_by_id"))
		}
	})
	t.Run("get_all_single", func(t *testing.T) {
		got := GetAllDSHCordisSubagents(item1)
		if !reflect.DeepEqual(got, []string{"reviewer"}) {
			t.Errorf("got %v want [reviewer]", got)
		}
	})
	t.Run("remove_single_becomes_empty", func(t *testing.T) {
		got := RemoveDSHCordisSubagent(item1, "reviewer")
		if got != wantStr("remove_single_becomes_empty") {
			t.Errorf("got %q want %q", got, wantStr("remove_single_becomes_empty"))
		}
	})
	t.Run("get_by_legacy_name", func(t *testing.T) {
		got, ok := GetDSHCordisSubagentItem(item2Legacy, "writer")
		if !ok || got != wantStr("get_by_legacy_name") {
			t.Errorf("got (%v,%q) want %q", ok, got, wantStr("get_by_legacy_name"))
		}
	})

	textMulti := otherPlugin + item1
	t.Run("get_all_multi", func(t *testing.T) {
		got := GetAllDSHCordisSubagents(textMulti)
		if !reflect.DeepEqual(got, []string{"reviewer"}) {
			t.Errorf("got %v want [reviewer] (other_plugin has no aikito marker)", got)
		}
	})
	t.Run("append_new_to_multi", func(t *testing.T) {
		newItem := "- id: aikito-subagent-newone\n  name: '@deepseek-ai/dsh-tool-subagent'\n  config:\n    toolName: newone\n    persona: |-\n      New\n"
		got := UpdateDSHCordisSubagent(textMulti, "newone", trimTrailingNewline(newItem))
		if got != wantStr("append_new_to_multi") {
			t.Errorf("got %q want %q", got, wantStr("append_new_to_multi"))
		}
	})
	t.Run("update_existing_in_multi", func(t *testing.T) {
		updatedItem1 := strings.Replace(item1, "spawn", "custom", 1)
		got := UpdateDSHCordisSubagent(textMulti, "reviewer", trimTrailingNewline(updatedItem1))
		if got != wantStr("update_existing_in_multi") {
			t.Errorf("got %q want %q", got, wantStr("update_existing_in_multi"))
		}
	})
	t.Run("remove_one_of_several", func(t *testing.T) {
		got := RemoveDSHCordisSubagent(textMulti, "reviewer")
		if got != wantStr("remove_one_of_several") {
			t.Errorf("got %q want %q", got, wantStr("remove_one_of_several"))
		}
	})
}

func trimTrailingNewline(s string) string {
	if len(s) > 0 && s[len(s)-1] == '\n' {
		return s[:len(s)-1]
	}
	return s
}
