package subagent

import (
	"bufio"
	"os"
	"strings"
)

// MarkerPrefix mirrors subagent_adapters.py's MARKER_PREFIX.
const MarkerPrefix = "generated by aikito from subagents/"

// GetMarkerText mirrors get_marker_text.
func GetMarkerText(name string) string {
	return "generated by aikito from subagents/" + name + ".md - edits will be overwritten"
}

// HasAikitoMarkerText mirrors has_aikito_marker_text.
func HasAikitoMarkerText(text string) bool {
	return strings.Contains(text, MarkerPrefix)
}

// HasAikitoMarker mirrors has_aikito_marker: scans at most the first 10
// lines of a file for the marker text, tolerating any read error (including
// invalid UTF-8, read as replacement characters like Python's
// errors="replace") by treating it as "no marker found" rather than failing.
func HasAikitoMarker(path string) bool {
	info, err := os.Stat(path)
	if err != nil || !info.Mode().IsRegular() {
		return false
	}
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for i := 0; i < 10 && scanner.Scan(); i++ {
		if strings.Contains(scanner.Text(), MarkerPrefix) {
			return true
		}
	}
	return false
}
