package subagent

import "testing"

// Cross-validated against SUBAGENT_ADAPTERS[...].validate_options in live
// Python, including the kind=="tools" bare-string auto-wrap quirk.
func TestValidateOptions(t *testing.T) {
	copilot := SUBAGENT_ADAPTERS["copilot_markdown"]

	t.Run("tools_bare_string_wrapped", func(t *testing.T) {
		got, err := copilot.ValidateOptions("copilot", "sub1", map[string]any{"tools": "single-tool"})
		if err != nil {
			t.Fatal(err)
		}
		tools, ok := got["tools"].([]any)
		if !ok || len(tools) != 1 || tools[0] != "single-tool" {
			t.Errorf("got %v, want tools wrapped to [single-tool]", got)
		}
	})

	t.Run("tools_list_ok", func(t *testing.T) {
		_, err := copilot.ValidateOptions("copilot", "sub1", map[string]any{"tools": []any{"a", "b"}})
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("unknown_field_rejected", func(t *testing.T) {
		_, err := copilot.ValidateOptions("copilot", "sub1", map[string]any{"bogus": "x"})
		if err == nil {
			t.Fatal("expected an error for an unknown field")
		}
	})

	t.Run("boolean_wrong_type_rejected", func(t *testing.T) {
		_, err := copilot.ValidateOptions("copilot", "sub1", map[string]any{"disable-model-invocation": "yes"})
		if err == nil {
			t.Fatal("expected an error for a non-boolean value")
		}
	})

	dsh := SUBAGENT_ADAPTERS["dsh_cordis_subagent"]
	t.Run("positive_integer_zero_rejected", func(t *testing.T) {
		_, err := dsh.ValidateOptions("dsh", "s", map[string]any{"maxTokens": int64(0)})
		if err == nil {
			t.Fatal("expected an error for maxTokens=0")
		}
	})
	t.Run("positive_integer_ok", func(t *testing.T) {
		_, err := dsh.ValidateOptions("dsh", "s", map[string]any{"maxTokens": int64(5)})
		if err != nil {
			t.Fatal(err)
		}
	})
	t.Run("background_bad_rejected", func(t *testing.T) {
		_, err := dsh.ValidateOptions("dsh", "s", map[string]any{"backgroundMode": "bad"})
		if err == nil {
			t.Fatal("expected an error for an invalid backgroundMode")
		}
	})
	t.Run("background_ok", func(t *testing.T) {
		_, err := dsh.ValidateOptions("dsh", "s", map[string]any{"backgroundMode": "one-shot"})
		if err != nil {
			t.Fatal(err)
		}
	})
}

func TestGetSubagentAdapterUnsupported(t *testing.T) {
	if _, err := GetSubagentAdapter("nonexistent_format"); err == nil {
		t.Fatal("expected an error for an unsupported config_format")
	}
}

func TestMarkerHelpers(t *testing.T) {
	name := "reviewer"
	marker := GetMarkerText(name)
	if marker != "generated by aikito from subagents/reviewer.md - edits will be overwritten" {
		t.Errorf("unexpected marker text: %q", marker)
	}
	if !HasAikitoMarkerText("prefix " + marker + " suffix") {
		t.Error("expected marker text to be found")
	}
	if HasAikitoMarkerText("no marker here") {
		t.Error("did not expect marker text to be found")
	}
}
